function Hd = filterNotch60_IIR
%FILTERNOTCH60_IIR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and DSP System Toolbox 9.9.
% Generated on: 14-Jun-2021 09:49:40

% IIR Notching filter designed using the IIRNOTCH function.

% All frequency values are in Hz.
Fs = 2000;  % Sampling Frequency

Fnotch = 60;  % Notch Frequency
BW     = 10;  % Bandwidth
Apass  = 1;   % Bandwidth Attenuation

[b, a] = iirnotch(Fnotch/(Fs/2), BW/(Fs/2), Apass);
Hd     = dfilt.df2(b, a);

% [EOF]
